import { defaultColors, defaultTheme } from './theme';
import { isModeAwareColor } from './colorValue';
import type { ThemeConfig } from './types';

// Header shared by every generation call — content-compared by callers before
// writing to skip a no-op disk write, so this text must be 100% deterministic
// for the same theme (no timestamps, no absolute paths).
const HEADER = `// AUTO-GENERATED by Kbach from your kbach.config.js — do not edit by hand.
// Regenerated automatically every time your dev server / Metro picks up a
// change to that file. Safe (and recommended) to add to .gitignore.
//
// Gives useColors()/useSpacing() full autocomplete and typo-catching for your
// custom colors/spacing keys with zero manual setup — see KbachCustomColors'
// doc comment in @kbach/ui if you'd rather hand-author this instead.
import '@kbach/ui';
`;

const IDENT_RE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

function propKey(name: string): string {
  return IDENT_RE.test(name) ? name : JSON.stringify(name);
}

/**
 * Generates the KbachCustomColors/KbachCustomSpacing module-augmentation
 * source for every color/spacing key `extend.theme` added beyond the built-in
 * defaults. Called by both the Vite plugin and the Babel plugin (@kbach/ui/babel-plugin) —
 * kept here, shared, so "which colors count as custom" and "flat string vs.
 * ColorScale" can't drift between the two.
 *
 * Returns '' (nothing to write) when the theme adds no custom colors or
 * spacing keys at all, so callers can skip writing/deleting a file for the
 * common case of a project still on the stock theme.
 */
export function generateKbachTypesDts(theme: ThemeConfig): string {
  const colorLines: string[] = [];
  for (const [name, value] of Object.entries(theme.colors)) {
    if (name in defaultColors) continue; // built-in — already typed by DefaultColorName
    // A flat string or a mode-aware { light, dark } pair both resolve to a
    // plain string at read time (useColors() collapses the pair to whichever
    // side is active) — only an actual shade scale needs the ColorScale shape.
    const isFlat = typeof value === 'string' || isModeAwareColor(value);
    colorLines.push(`    ${propKey(name)}: ${isFlat ? 'string' : 'ColorScale'};`);
  }

  const spacingLines: string[] = [];
  for (const key of Object.keys(theme.spacing)) {
    if (key in defaultTheme.spacing) continue; // built-in — already typed by DefaultSpacingKey
    // Only the KEY is ever read from KbachCustomSpacing (see useSpacing.ts) —
    // the value type is irrelevant, `true` is just a short, valid placeholder.
    spacingLines.push(`    ${propKey(key)}: true;`);
  }

  if (colorLines.length === 0 && spacingLines.length === 0) return '';

  const body = [
    colorLines.length > 0
      ? `  interface KbachCustomColors {\n${colorLines.join('\n')}\n  }`
      : null,
    spacingLines.length > 0
      ? `  interface KbachCustomSpacing {\n${spacingLines.join('\n')}\n  }`
      : null,
  ].filter((s): s is string => s !== null).join('\n\n');

  return `${HEADER}\ndeclare module '@kbach/ui' {\n${body}\n}\n`;
}
