#!/usr/bin/env node
// Generates a TS file exporting Kbach's default color palette, sourced from
// Rust (packages/core-engine/src/theme.rs's DEFAULT_COLORS) via the
// already-synchronous Node-target WASM build (dist-node/, not dist/ — see
// the Phase 16 plan for why the browser target can't be used the same way).
//
// Usage: node generate-palette.mjs <output-path-relative-to-cwd>
// Run manually when the Rust palette changes — not wired into any
// prebuild/pretest hook, see packages/react's and packages/react-native's
// package.json "generate:colors" scripts.

import { createRequire } from 'module';
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const require = createRequire(import.meta.url);
const thisDir = dirname(fileURLToPath(import.meta.url));

const outputArg = process.argv[2];
if (!outputArg) {
  console.error('Usage: node generate-palette.mjs <output-path>');
  process.exit(1);
}

// require(), not import — dist-node/kbach_core_engine.js is wasm-pack's
// `--target nodejs` CommonJS output; requiring it directly sidesteps any
// ESM/CJS interop ambiguity for a plain script invocation like this one.
const { default_colors_json } = require(join(thisDir, '..', 'dist-node', 'kbach_core_engine.js'));

const palette = JSON.parse(default_colors_json());
const entries = Object.entries(palette)
  .map(([key, value]) => `  '${key}': '${value}',`)
  .join('\n');

const output = [
  '// Generated by Kbach — do not edit.',
  '// Regenerate: npm run generate:colors (after changing',
  '// packages/core-engine/src/theme.rs\'s DEFAULT_COLORS and rebuilding',
  "// core-engine's Node-target WASM build).",
  '//',
  '// Source of truth: packages/core-engine/src/theme.rs\'s DEFAULT_COLORS —',
  '// see that const\'s doc comment for why this is generated rather than a',
  '// second hand-maintained copy.',
  'export const PALETTE: Record<string, string> = {',
  entries,
  '};',
  '',
].join('\n');

const outputPath = join(process.cwd(), outputArg);
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, 'utf-8');
console.log(`Wrote ${Object.keys(palette).length} colors to ${outputPath}`);
