import type { RuleEntry } from './wasmNode';
import type { ThemeConfig } from '../theme';
import { buildColorVarMap, buildSpacingVarMap, applyVarMap } from './cssVars';
import { mergeResponsiveMediaBlocks } from './mediaMerge';
import { prettifyCSS } from './prettify';
import { buildResetCSS } from '../reset';

// Exported so vite-plugin/index.ts's auto-detection (findMainCSSFile) can
// recognize an existing marked file without duplicating these literals.
export const KBACH_START = '/* kbach:start */';
export const KBACH_END = '/* kbach:end */';

/**
 * Assembles the kbach.css body from every currently-referenced token's
 * resolved rules, piped through: merge same-breakpoint @media blocks ->
 * extract repeated color/spacing values into :root custom properties ->
 * pretty-print. Var-substitution and media-merging both operate on the
 * compact one-line-per-rule form css.rs produces (matching old-kbach's own
 * pipeline order) — prettify runs last, once the text is otherwise final.
 *
 * `usedTags` (from scan.ts's scanUsedTags, unioned across every scanned
 * file) prunes the base reset down to only the HTML elements this project
 * actually renders — pass `undefined` to get the full, unpruned reset
 * (e.g. from a test with no real source to scan).
 */
export function formatKbachCSS(tokenRules: Map<string, RuleEntry[]>, theme: ThemeConfig, usedTags?: Set<string>): string {
  const allEntries: RuleEntry[] = [];
  for (const rules of tokenRules.values()) {
    for (const entry of rules) allEntries.push(entry);
  }
  // Stable sort by cascade order — mirrors kb.ts's runtime sorted-insertion
  // (see that module's own comment): which same-specificity rule wins a
  // cascade tie must depend on `order` (registry.rs's modifier tiers, and
  // background.rs's from-*/via-*/to-* gradient-stop sub-tier), not on
  // whichever token this build's source scan happened to discover first.
  // `Array.prototype.sort` is a stable sort (ES2019+), so same-order rules
  // keep their original relative (scan-discovery) order.
  allEntries.sort((a, b) => a.order - b.order);
  const allRules = allEntries.map((e) => e.rule);

  const merged = mergeResponsiveMediaBlocks(allRules);
  const compact = merged.join('\n');

  const colorMap = buildColorVarMap(theme, compact);
  const spacingMap = buildSpacingVarMap(theme, compact);
  const { text, declarations } = applyVarMap(compact, colorMap, spacingMap);

  const lines: string[] = ['/* Generated by Kbach — do not edit */', '', buildResetCSS(usedTags)];
  // `--kb-dark-mode` always goes in :root, even with zero color/spacing
  // declarations to extract — darkModeStore.ts reads it back via
  // getComputedStyle at runtime startup so an app using ONLY this static
  // plugin never has to separately tell applyKbachConfig() which strategy
  // the CSS below was actually built for (see that module's own doc
  // comment for the full reasoning). Kept as a bare CSS custom-ident, not a
  // quoted string, since every valid DarkModeStrategy value ('attribute'/
  // 'class'/'media') already is one — no quote-stripping needed to read it
  // back.
  lines.push('', ':root {', `  --kb-dark-mode: ${theme.darkMode};`);
  for (const [varName, val] of declarations) lines.push(`  ${varName}: ${val};`);
  lines.push('}');
  lines.push('', prettifyCSS(text));

  return lines.join('\n');
}

/**
 * Writes `css` between the KBACH_START/END markers in `filePath`, preserving
 * any content the user placed outside them. Returns whether the file's
 * content actually changed (so callers can skip a spurious HMR/watcher
 * notification when a rebuild produced byte-identical output).
 */
export function writeKbachToFile(
  filePath: string,
  css: string,
  readFile: (path: string) => string,
  writeFile: (path: string, content: string) => void,
): boolean {
  let existing = '';
  try {
    existing = readFile(filePath);
  } catch {
    // File doesn't exist yet — treated as empty, block gets appended below.
  }

  const block = `${KBACH_START}\n${css}\n${KBACH_END}`;
  const start = existing.indexOf(KBACH_START);
  const end = existing.indexOf(KBACH_END);
  const next =
    start !== -1 && end !== -1 && end > start
      ? existing.slice(0, start) + block + existing.slice(end + KBACH_END.length)
      : existing
        ? `${existing}\n\n${block}`
        : block;

  if (next === existing) return false;
  writeFile(filePath, next);
  return true;
}
