import type { RuleEntry } from './wasmNode';
import type { ThemeConfig } from '../theme';
import { buildColorVarMap, buildSpacingVarMap, applyVarMap } from './cssVars';
import { mergeResponsiveMediaBlocks } from './mediaMerge';
import { prettifyCSS } from './prettify';

const KBACH_START = '/* kbach:start */';
const KBACH_END = '/* kbach:end */';

/**
 * Assembles the kbach.css body from every currently-referenced token's
 * resolved rules, piped through: merge same-breakpoint @media blocks ->
 * extract repeated color/spacing values into :root custom properties ->
 * pretty-print. Var-substitution and media-merging both operate on the
 * compact one-line-per-rule form css.rs produces (matching old-kbach's own
 * pipeline order) — prettify runs last, once the text is otherwise final.
 */
export function formatKbachCSS(tokenRules: Map<string, RuleEntry[]>, theme: ThemeConfig): string {
  const allRules: string[] = [];
  for (const rules of tokenRules.values()) {
    for (const { rule } of rules) allRules.push(rule);
  }

  const merged = mergeResponsiveMediaBlocks(allRules);
  const compact = merged.join('\n');

  const colorMap = buildColorVarMap(theme, compact);
  const spacingMap = buildSpacingVarMap(theme, compact);
  const { text, declarations } = applyVarMap(compact, colorMap, spacingMap);

  const lines: string[] = ['/* Generated by Kbach — do not edit */'];
  if (declarations.size > 0) {
    lines.push('', ':root {');
    for (const [varName, val] of declarations) lines.push(`  ${varName}: ${val};`);
    lines.push('}');
  }
  lines.push('', prettifyCSS(text));

  return lines.join('\n');
}

/**
 * Writes `css` between the KBACH_START/END markers in `filePath`, preserving
 * any content the user placed outside them. Returns whether the file's
 * content actually changed (so callers can skip a spurious HMR/watcher
 * notification when a rebuild produced byte-identical output).
 */
export function writeKbachToFile(
  filePath: string,
  css: string,
  readFile: (path: string) => string,
  writeFile: (path: string, content: string) => void,
): boolean {
  let existing = '';
  try {
    existing = readFile(filePath);
  } catch {
    // File doesn't exist yet — treated as empty, block gets appended below.
  }

  const block = `${KBACH_START}\n${css}\n${KBACH_END}`;
  const start = existing.indexOf(KBACH_START);
  const end = existing.indexOf(KBACH_END);
  const next =
    start !== -1 && end !== -1 && end > start
      ? existing.slice(0, start) + block + existing.slice(end + KBACH_END.length)
      : existing
        ? `${existing}\n\n${block}`
        : block;

  if (next === existing) return false;
  writeFile(filePath, next);
  return true;
}
